# Generated by Django 4.2.3 on 2023-08-04 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_basketitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketitem',
            name='count',
        ),
    ]
