# Generated by Django 4.2.3 on 2023-08-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_remove_basketitem_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
