# Generated by Django 4.2.3 on 2023-08-04 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_basketitem_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BasketItem',
        ),
    ]
