# Generated by Django 4.2.3 on 2023-08-04 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_basketitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BasketItem',
        ),
    ]
