# Generated by Django 4.2.3 on 2023-08-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_orded_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='orded',
            name='phone_code',
            field=models.CharField(choices=[('+994', '+994'), ('+999', '+999'), ('+012', '+012')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orded',
            name='mobile',
            field=models.CharField(max_length=20),
        ),
    ]
