# Generated by Django 4.2.3 on 2023-08-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_remove_orded_used_coupun_orded_coupun_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
