# Generated by Django 4.2.3 on 2023-08-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_orderproduct_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orded',
            old_name='coupun_code',
            new_name='coupon_code',
        ),
        migrations.RemoveField(
            model_name='orded',
            name='coupun_discount',
        ),
        migrations.AddField(
            model_name='orded',
            name='coupon_discount',
            field=models.IntegerField(default=0),
        ),
    ]
