# Generated by Django 4.2.3 on 2023-07-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_category_general_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prouduct',
            name='general',
            field=models.ManyToManyField(related_name='prouduct', to='shop.generalcategory'),
        ),
    ]
