# Generated by Django 4.2.3 on 2023-08-02 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_prouduct_general'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prouduct',
            options={'ordering': ['-created']},
        ),
    ]
