# Generated by Django 4.2.3 on 2023-08-03 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_prouduct_star_count_prouduct_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prouduct',
            name='star_count',
        ),
        migrations.RemoveField(
            model_name='prouduct',
            name='user',
        ),
    ]
