# Generated by Django 4.2.3 on 2023-08-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_prouduct_star_count_remove_prouduct_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prouduct',
            name='title',
            field=models.TextField(max_length=50),
        ),
    ]
