# Generated by Django 4.2.3 on 2023-08-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_prouduct_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='similiar_products',
            field=models.ManyToManyField(blank=True, related_name='related_products', to='shop.prouduct'),
        ),
    ]
