# Generated by Django 4.2.3 on 2023-08-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_category_similiar_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='similiar_products',
            field=models.ManyToManyField(blank=True, related_name='similiar_products', to='shop.prouduct'),
        ),
    ]
