# Generated by Django 4.2.3 on 2023-08-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_category_similar_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='prouduct',
            name='slug',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
